_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 2
                - 3
                - 12
                - 41
                - 48
                - 55
            "2":
                - 1
                - 2
                - 3
                - 12
                - 41
                - 48
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.19.7
            "8":
                - 1
                - 5
            "12": 0.19.7
            "13": linux-x86_64
HausdorffDistance:
    value: 0
batch_size:
    value: 5
dice:
    value: 0
layers:
    value: 5
loss function:
    value: DiceLoss()
lr:
    value: 0.001
parameters:
    value: 406804
transform:
    value:
        - <dataset.LoadVesselData object at 0x7f9bb7612d10>
        - <monai.transforms.utility.dictionary.AddChanneld object at 0x7f9bb7612c80>
        - <monai.transforms.intensity.dictionary.ScaleIntensityd object at 0x7f9bb7613640>
        - <monai.transforms.spatial.dictionary.RandFlipd object at 0x7f9bb7670f40>
        - <monai.transforms.spatial.dictionary.RandRotated object at 0x7f9bb7673a60>
        - <monai.transforms.croppad.dictionary.RandSpatialCropd object at 0x7f9bb7671a20>
